# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Qt\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 771)
        MainWindow.setMinimumSize(QtCore.QSize(700, 665))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Controls = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Controls.sizePolicy().hasHeightForWidth())
        self.Controls.setSizePolicy(sizePolicy)
        self.Controls.setMinimumSize(QtCore.QSize(150, 580))
        self.Controls.setMaximumSize(QtCore.QSize(150, 580))
        self.Controls.setObjectName("Controls")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Controls)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.TreeControl = QtWidgets.QFrame(self.Controls)
        self.TreeControl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TreeControl.sizePolicy().hasHeightForWidth())
        self.TreeControl.setSizePolicy(sizePolicy)
        self.TreeControl.setMinimumSize(QtCore.QSize(150, 200))
        self.TreeControl.setMaximumSize(QtCore.QSize(150, 200))
        self.TreeControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TreeControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TreeControl.setObjectName("TreeControl")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TreeControl)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Epsilon = QtWidgets.QLabel(self.TreeControl)
        self.Epsilon.setObjectName("Epsilon")
        self.gridLayout_3.addWidget(self.Epsilon, 4, 0, 1, 1)
        self.MinDepth = QtWidgets.QLabel(self.TreeControl)
        self.MinDepth.setObjectName("MinDepth")
        self.gridLayout_3.addWidget(self.MinDepth, 0, 0, 1, 1)
        self.BuildTreeAction = QtWidgets.QPushButton(self.TreeControl)
        self.BuildTreeAction.setMinimumSize(QtCore.QSize(0, 20))
        self.BuildTreeAction.setObjectName("BuildTreeAction")
        self.gridLayout_3.addWidget(self.BuildTreeAction, 6, 0, 1, 2)
        self.MaxDepth = QtWidgets.QLabel(self.TreeControl)
        self.MaxDepth.setObjectName("MaxDepth")
        self.gridLayout_3.addWidget(self.MaxDepth, 2, 0, 1, 1)
        self.MaxDepthValue = QtWidgets.QSpinBox(self.TreeControl)
        self.MaxDepthValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaxDepthValue.setProperty("value", 8)
        self.MaxDepthValue.setObjectName("MaxDepthValue")
        self.gridLayout_3.addWidget(self.MaxDepthValue, 2, 1, 1, 1)
        self.EpsilonValue = QtWidgets.QDoubleSpinBox(self.TreeControl)
        self.EpsilonValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EpsilonValue.setDecimals(4)
        self.EpsilonValue.setMaximum(1.0)
        self.EpsilonValue.setSingleStep(0.01)
        self.EpsilonValue.setProperty("value", 0.5)
        self.EpsilonValue.setObjectName("EpsilonValue")
        self.gridLayout_3.addWidget(self.EpsilonValue, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.MinDepthValue = QtWidgets.QSpinBox(self.TreeControl)
        self.MinDepthValue.setWrapping(True)
        self.MinDepthValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MinDepthValue.setMaximum(999)
        self.MinDepthValue.setProperty("value", 2)
        self.MinDepthValue.setObjectName("MinDepthValue")
        self.gridLayout_3.addWidget(self.MinDepthValue, 0, 1, 1, 1)
        self.TreeProgress = QtWidgets.QProgressBar(self.TreeControl)
        self.TreeProgress.setProperty("value", 0)
        self.TreeProgress.setTextVisible(False)
        self.TreeProgress.setObjectName("TreeProgress")
        self.gridLayout_3.addWidget(self.TreeProgress, 7, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.TreeControl)
        self.line = QtWidgets.QFrame(self.Controls)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.VisControl = QtWidgets.QFrame(self.Controls)
        self.VisControl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VisControl.sizePolicy().hasHeightForWidth())
        self.VisControl.setSizePolicy(sizePolicy)
        self.VisControl.setMinimumSize(QtCore.QSize(150, 210))
        self.VisControl.setMaximumSize(QtCore.QSize(150, 210))
        self.VisControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VisControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VisControl.setObjectName("VisControl")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.VisControl)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.VisControl)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.VisControl)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 6, 0, 1, 1)
        self.ColorValue = QtWidgets.QComboBox(self.VisControl)
        self.ColorValue.setEnabled(False)
        self.ColorValue.setObjectName("ColorValue")
        self.ColorValue.addItem("")
        self.ColorValue.addItem("")
        self.gridLayout_4.addWidget(self.ColorValue, 6, 1, 1, 2)
        self.HierDepthNum = QtWidgets.QSpinBox(self.VisControl)
        self.HierDepthNum.setMinimumSize(QtCore.QSize(40, 0))
        self.HierDepthNum.setMaximumSize(QtCore.QSize(80, 16777215))
        self.HierDepthNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HierDepthNum.setObjectName("HierDepthNum")
        self.gridLayout_4.addWidget(self.HierDepthNum, 5, 2, 1, 1)
        self.HierDepthSlider = QtWidgets.QSlider(self.VisControl)
        self.HierDepthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.HierDepthSlider.setObjectName("HierDepthSlider")
        self.gridLayout_4.addWidget(self.HierDepthSlider, 5, 0, 1, 2)
        self.CreateHierarchy = QtWidgets.QPushButton(self.VisControl)
        self.CreateHierarchy.setObjectName("CreateHierarchy")
        self.gridLayout_4.addWidget(self.CreateHierarchy, 1, 0, 1, 3)
        self.PlacePaths = QtWidgets.QPushButton(self.VisControl)
        self.PlacePaths.setObjectName("PlacePaths")
        self.gridLayout_4.addWidget(self.PlacePaths, 0, 0, 1, 3)
        self.PathProgress = QtWidgets.QProgressBar(self.VisControl)
        self.PathProgress.setProperty("value", 0)
        self.PathProgress.setTextVisible(False)
        self.PathProgress.setObjectName("PathProgress")
        self.gridLayout_4.addWidget(self.PathProgress, 2, 0, 1, 3)
        self.Seperator = QtWidgets.QFrame(self.VisControl)
        self.Seperator.setFrameShape(QtWidgets.QFrame.HLine)
        self.Seperator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Seperator.setObjectName("Seperator")
        self.gridLayout_4.addWidget(self.Seperator, 3, 0, 1, 3)
        self.HierDepthText = QtWidgets.QLabel(self.VisControl)
        self.HierDepthText.setMaximumSize(QtCore.QSize(16777215, 25))
        self.HierDepthText.setObjectName("HierDepthText")
        self.gridLayout_4.addWidget(self.HierDepthText, 4, 0, 1, 3)
        self.AreaValue = QtWidgets.QComboBox(self.VisControl)
        self.AreaValue.setMinimumSize(QtCore.QSize(0, 0))
        self.AreaValue.setObjectName("AreaValue")
        self.AreaValue.addItem("")
        self.AreaValue.addItem("")
        self.gridLayout_4.addWidget(self.AreaValue, 7, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.VisControl)
        self.PlotControl = QtWidgets.QFrame(self.Controls)
        self.PlotControl.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotControl.sizePolicy().hasHeightForWidth())
        self.PlotControl.setSizePolicy(sizePolicy)
        self.PlotControl.setMinimumSize(QtCore.QSize(150, 180))
        self.PlotControl.setMaximumSize(QtCore.QSize(150, 180))
        self.PlotControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PlotControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PlotControl.setObjectName("PlotControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PlotControl)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yNum = QtWidgets.QDoubleSpinBox(self.PlotControl)
        self.yNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.yNum.setMinimum(0.01)
        self.yNum.setMaximum(99999.0)
        self.yNum.setSingleStep(0.01)
        self.yNum.setProperty("value", 1.0)
        self.yNum.setObjectName("yNum")
        self.gridLayout_2.addWidget(self.yNum, 4, 1, 1, 1)
        self.xNum = QtWidgets.QDoubleSpinBox(self.PlotControl)
        self.xNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xNum.setMinimum(0.01)
        self.xNum.setMaximum(99999.0)
        self.xNum.setSingleStep(0.01)
        self.xNum.setProperty("value", 1.0)
        self.xNum.setObjectName("xNum")
        self.gridLayout_2.addWidget(self.xNum, 2, 1, 1, 1)
        self.yLabel = QtWidgets.QLabel(self.PlotControl)
        self.yLabel.setObjectName("yLabel")
        self.gridLayout_2.addWidget(self.yLabel, 3, 0, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.PlotControl)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout_2.addWidget(self.zLabel, 5, 0, 1, 1)
        self.yScale = QtWidgets.QSlider(self.PlotControl)
        self.yScale.setMinimum(1)
        self.yScale.setMaximum(1000)
        self.yScale.setSingleStep(1)
        self.yScale.setPageStep(100)
        self.yScale.setProperty("value", 100)
        self.yScale.setOrientation(QtCore.Qt.Horizontal)
        self.yScale.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.yScale.setTickInterval(99)
        self.yScale.setObjectName("yScale")
        self.gridLayout_2.addWidget(self.yScale, 4, 0, 1, 1)
        self.xLabel = QtWidgets.QLabel(self.PlotControl)
        self.xLabel.setObjectName("xLabel")
        self.gridLayout_2.addWidget(self.xLabel, 1, 0, 1, 1)
        self.zScale = QtWidgets.QSlider(self.PlotControl)
        self.zScale.setMinimum(1)
        self.zScale.setMaximum(1000)
        self.zScale.setPageStep(100)
        self.zScale.setProperty("value", 100)
        self.zScale.setOrientation(QtCore.Qt.Horizontal)
        self.zScale.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.zScale.setTickInterval(99)
        self.zScale.setObjectName("zScale")
        self.gridLayout_2.addWidget(self.zScale, 6, 0, 1, 1)
        self.xScale = QtWidgets.QSlider(self.PlotControl)
        self.xScale.setMinimum(1)
        self.xScale.setMaximum(1000)
        self.xScale.setPageStep(100)
        self.xScale.setProperty("value", 100)
        self.xScale.setSliderPosition(100)
        self.xScale.setOrientation(QtCore.Qt.Horizontal)
        self.xScale.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.xScale.setTickInterval(24975)
        self.xScale.setObjectName("xScale")
        self.gridLayout_2.addWidget(self.xScale, 2, 0, 1, 1)
        self.zNum = QtWidgets.QDoubleSpinBox(self.PlotControl)
        self.zNum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zNum.setMinimum(0.01)
        self.zNum.setMaximum(1000.0)
        self.zNum.setSingleStep(0.01)
        self.zNum.setProperty("value", 1.0)
        self.zNum.setObjectName("zNum")
        self.gridLayout_2.addWidget(self.zNum, 6, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.PlotControl)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.PlotControl)
        self.gridLayout.addWidget(self.Controls, 0, 0, 2, 1)
        self.Data = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Data.sizePolicy().hasHeightForWidth())
        self.Data.setSizePolicy(sizePolicy)
        self.Data.setMinimumSize(QtCore.QSize(120, 620))
        self.Data.setMaximumSize(QtCore.QSize(200, 800))
        self.Data.setObjectName("Data")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Data)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FileStatus = QtWidgets.QFrame(self.Data)
        self.FileStatus.setMinimumSize(QtCore.QSize(0, 120))
        self.FileStatus.setMaximumSize(QtCore.QSize(16777215, 120))
        self.FileStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FileStatus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FileStatus.setObjectName("FileStatus")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.FileStatus)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Status = QtWidgets.QLabel(self.FileStatus)
        self.Status.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Status.setObjectName("Status")
        self.gridLayout_5.addWidget(self.Status, 0, 0, 1, 1)
        self.StatusValue = QtWidgets.QLabel(self.FileStatus)
        self.StatusValue.setMaximumSize(QtCore.QSize(16777215, 40))
        self.StatusValue.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.StatusValue.setWordWrap(True)
        self.StatusValue.setObjectName("StatusValue")
        self.gridLayout_5.addWidget(self.StatusValue, 1, 0, 1, 1)
        self.SavedState = QtWidgets.QLabel(self.FileStatus)
        self.SavedState.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SavedState.setObjectName("SavedState")
        self.gridLayout_5.addWidget(self.SavedState, 4, 0, 1, 1)
        self.SavedStateVal = QtWidgets.QLabel(self.FileStatus)
        self.SavedStateVal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SavedStateVal.setAlignment(QtCore.Qt.AlignCenter)
        self.SavedStateVal.setWordWrap(True)
        self.SavedStateVal.setObjectName("SavedStateVal")
        self.gridLayout_5.addWidget(self.SavedStateVal, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.FileStatus)
        self.line_4 = QtWidgets.QFrame(self.Data)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.Dimensions = QtWidgets.QLabel(self.Data)
        self.Dimensions.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Dimensions.setObjectName("Dimensions")
        self.verticalLayout.addWidget(self.Dimensions)
        self.DimensionsValue = QtWidgets.QLabel(self.Data)
        self.DimensionsValue.setMinimumSize(QtCore.QSize(100, 40))
        self.DimensionsValue.setMaximumSize(QtCore.QSize(16777215, 40))
        self.DimensionsValue.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.DimensionsValue.setWordWrap(True)
        self.DimensionsValue.setObjectName("DimensionsValue")
        self.verticalLayout.addWidget(self.DimensionsValue)
        self.TreeData = QtWidgets.QFrame(self.Data)
        self.TreeData.setMinimumSize(QtCore.QSize(0, 160))
        self.TreeData.setMaximumSize(QtCore.QSize(16777215, 160))
        self.TreeData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TreeData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TreeData.setObjectName("TreeData")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.TreeData)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.LeafCount = QtWidgets.QLabel(self.TreeData)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LeafCount.sizePolicy().hasHeightForWidth())
        self.LeafCount.setSizePolicy(sizePolicy)
        self.LeafCount.setMaximumSize(QtCore.QSize(16777215, 20))
        self.LeafCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LeafCount.setWordWrap(True)
        self.LeafCount.setObjectName("LeafCount")
        self.gridLayout_6.addWidget(self.LeafCount, 0, 0, 1, 1)
        self.LeafCountValue = QtWidgets.QLabel(self.TreeData)
        self.LeafCountValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.LeafCountValue.setAlignment(QtCore.Qt.AlignCenter)
        self.LeafCountValue.setObjectName("LeafCountValue")
        self.gridLayout_6.addWidget(self.LeafCountValue, 1, 0, 1, 1)
        self.Sim = QtWidgets.QLabel(self.TreeData)
        self.Sim.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Sim.setWordWrap(True)
        self.Sim.setObjectName("Sim")
        self.gridLayout_6.addWidget(self.Sim, 2, 0, 1, 1)
        self.Size = QtWidgets.QLabel(self.TreeData)
        self.Size.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Size.setWordWrap(True)
        self.Size.setObjectName("Size")
        self.gridLayout_6.addWidget(self.Size, 5, 0, 1, 1)
        self.SizeValue = QtWidgets.QLabel(self.TreeData)
        self.SizeValue.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SizeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.SizeValue.setWordWrap(True)
        self.SizeValue.setObjectName("SizeValue")
        self.gridLayout_6.addWidget(self.SizeValue, 6, 0, 1, 1)
        self.SimValue = QtWidgets.QLabel(self.TreeData)
        self.SimValue.setMinimumSize(QtCore.QSize(80, 40))
        self.SimValue.setMaximumSize(QtCore.QSize(16777215, 40))
        self.SimValue.setAlignment(QtCore.Qt.AlignCenter)
        self.SimValue.setWordWrap(True)
        self.SimValue.setObjectName("SimValue")
        self.gridLayout_6.addWidget(self.SimValue, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.TreeData)
        self.line_3 = QtWidgets.QFrame(self.Data)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.VisData = QtWidgets.QFrame(self.Data)
        self.VisData.setMinimumSize(QtCore.QSize(80, 100))
        self.VisData.setMaximumSize(QtCore.QSize(100, 120))
        self.VisData.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VisData.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VisData.setObjectName("VisData")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.VisData)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.HierDepth = QtWidgets.QLabel(self.VisData)
        self.HierDepth.setMinimumSize(QtCore.QSize(0, 30))
        self.HierDepth.setMaximumSize(QtCore.QSize(16777215, 30))
        self.HierDepth.setWordWrap(True)
        self.HierDepth.setObjectName("HierDepth")
        self.gridLayout_7.addWidget(self.HierDepth, 0, 0, 1, 1)
        self.HierDepthVal = QtWidgets.QLabel(self.VisData)
        self.HierDepthVal.setMinimumSize(QtCore.QSize(0, 15))
        self.HierDepthVal.setMaximumSize(QtCore.QSize(16777215, 15))
        self.HierDepthVal.setAlignment(QtCore.Qt.AlignCenter)
        self.HierDepthVal.setObjectName("HierDepthVal")
        self.gridLayout_7.addWidget(self.HierDepthVal, 1, 0, 1, 1)
        self.LastSim = QtWidgets.QLabel(self.VisData)
        self.LastSim.setMinimumSize(QtCore.QSize(0, 30))
        self.LastSim.setMaximumSize(QtCore.QSize(16777215, 30))
        self.LastSim.setWordWrap(True)
        self.LastSim.setObjectName("LastSim")
        self.gridLayout_7.addWidget(self.LastSim, 2, 0, 1, 1)
        self.LastSimVal = QtWidgets.QLabel(self.VisData)
        self.LastSimVal.setMinimumSize(QtCore.QSize(0, 20))
        self.LastSimVal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.LastSimVal.setAlignment(QtCore.Qt.AlignCenter)
        self.LastSimVal.setObjectName("LastSimVal")
        self.gridLayout_7.addWidget(self.LastSimVal, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.VisData)
        self.gridLayout.addWidget(self.Data, 0, 2, 2, 1)
        self.plotWidget = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setMinimumSize(QtCore.QSize(230, 580))
        self.plotWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.plotWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plotWidget.setLineWidth(1)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 1, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHighlighting = QtWidgets.QMenu(self.menuView)
        self.menuHighlighting.setObjectName("menuHighlighting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionShow_Wireframe = QtWidgets.QAction(MainWindow)
        self.actionShow_Wireframe.setCheckable(True)
        self.actionShow_Wireframe.setChecked(True)
        self.actionShow_Wireframe.setObjectName("actionShow_Wireframe")
        self.actionDraw_Inner_bounds = QtWidgets.QAction(MainWindow)
        self.actionDraw_Inner_bounds.setObjectName("actionDraw_Inner_bounds")
        self.actionShow_Inner_Bounds = QtWidgets.QAction(MainWindow)
        self.actionShow_Inner_Bounds.setCheckable(True)
        self.actionShow_Inner_Bounds.setEnabled(True)
        self.actionShow_Inner_Bounds.setObjectName("actionShow_Inner_Bounds")
        self.actionShow_z_Lines = QtWidgets.QAction(MainWindow)
        self.actionShow_z_Lines.setCheckable(True)
        self.actionShow_z_Lines.setEnabled(True)
        self.actionShow_z_Lines.setObjectName("actionShow_z_Lines")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionHighlight_last_children = QtWidgets.QAction(MainWindow)
        self.actionHighlight_last_children.setCheckable(True)
        self.actionHighlight_last_children.setObjectName("actionHighlight_last_children")
        self.actionLast_Merge = QtWidgets.QAction(MainWindow)
        self.actionLast_Merge.setCheckable(True)
        self.actionLast_Merge.setChecked(True)
        self.actionLast_Merge.setObjectName("actionLast_Merge")
        self.actionLast_Children = QtWidgets.QAction(MainWindow)
        self.actionLast_Children.setCheckable(True)
        self.actionLast_Children.setChecked(True)
        self.actionLast_Children.setObjectName("actionLast_Children")
        self.actionAge = QtWidgets.QAction(MainWindow)
        self.actionAge.setCheckable(True)
        self.actionAge.setChecked(True)
        self.actionAge.setObjectName("actionAge")
        self.actionSimilarity = QtWidgets.QAction(MainWindow)
        self.actionSimilarity.setObjectName("actionSimilarity")
        self.actionSimilar_members_at_point = QtWidgets.QAction(MainWindow)
        self.actionSimilar_members_at_point.setObjectName("actionSimilar_members_at_point")
        self.actionMerge_Size = QtWidgets.QAction(MainWindow)
        self.actionMerge_Size.setCheckable(True)
        self.actionMerge_Size.setChecked(True)
        self.actionMerge_Size.setObjectName("actionMerge_Size")
        self.actionOpen_Preferences = QtWidgets.QAction(MainWindow)
        self.actionOpen_Preferences.setObjectName("actionOpen_Preferences")
        self.actionLoad_data = QtWidgets.QAction(MainWindow)
        self.actionLoad_data.setObjectName("actionLoad_data")
        self.actionShow_Timeslices = QtWidgets.QAction(MainWindow)
        self.actionShow_Timeslices.setCheckable(True)
        self.actionShow_Timeslices.setChecked(True)
        self.actionShow_Timeslices.setObjectName("actionShow_Timeslices")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_data)
        self.menuFile.addAction(self.actionSave_as)
        self.menuHighlighting.addAction(self.actionLast_Merge)
        self.menuHighlighting.addAction(self.actionLast_Children)
        self.menuView.addAction(self.actionShow_Wireframe)
        self.menuView.addAction(self.actionShow_Timeslices)
        self.menuView.addAction(self.actionShow_Inner_Bounds)
        self.menuView.addAction(self.actionShow_z_Lines)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuHighlighting.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.HierDepthSlider.valueChanged['int'].connect(self.HierDepthNum.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Epsilon.setText(_translate("MainWindow", "Epsilon"))
        self.MinDepth.setText(_translate("MainWindow", "Min Depth"))
        self.BuildTreeAction.setText(_translate("MainWindow", "Build Tree"))
        self.MaxDepth.setText(_translate("MainWindow", "Max Depth"))
        self.label_4.setText(_translate("MainWindow", "Area:"))
        self.label_3.setText(_translate("MainWindow", "Color:"))
        self.ColorValue.setItemText(0, _translate("MainWindow", "Age"))
        self.ColorValue.setItemText(1, _translate("MainWindow", "Similarity"))
        self.CreateHierarchy.setText(_translate("MainWindow", "Create Hierarchy"))
        self.PlacePaths.setText(_translate("MainWindow", "Place Paths"))
        self.HierDepthText.setText(_translate("MainWindow", "Hierarchy Depth"))
        self.AreaValue.setItemText(0, _translate("MainWindow", "# Merges"))
        self.AreaValue.setItemText(1, _translate("MainWindow", "Group Size"))
        self.yLabel.setText(_translate("MainWindow", "y-Scale"))
        self.zLabel.setText(_translate("MainWindow", "z-Scale"))
        self.xLabel.setText(_translate("MainWindow", "x-Scale"))
        self.Status.setText(_translate("MainWindow", "Status:"))
        self.StatusValue.setText(_translate("MainWindow", "No File"))
        self.SavedState.setText(_translate("MainWindow", "Saved:"))
        self.SavedStateVal.setText(_translate("MainWindow", "False"))
        self.Dimensions.setText(_translate("MainWindow", "Dimensions:"))
        self.DimensionsValue.setText(_translate("MainWindow", " [||] - [||]"))
        self.LeafCount.setText(_translate("MainWindow", "Leaf Count:"))
        self.LeafCountValue.setText(_translate("MainWindow", "0"))
        self.Sim.setText(_translate("MainWindow", "Similarity:"))
        self.Size.setText(_translate("MainWindow", "Size:"))
        self.SizeValue.setText(_translate("MainWindow", "[-]"))
        self.SimValue.setText(_translate("MainWindow", "[-]"))
        self.HierDepth.setText(_translate("MainWindow", "Hierarchy size:"))
        self.HierDepthVal.setText(_translate("MainWindow", "0"))
        self.LastSim.setText(_translate("MainWindow", "Last similarity:"))
        self.LastSimVal.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHighlighting.setTitle(_translate("MainWindow", "Highlighting"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionShow_Wireframe.setText(_translate("MainWindow", "Show bounding box"))
        self.actionDraw_Inner_bounds.setText(_translate("MainWindow", "Draw inner bounds"))
        self.actionShow_Inner_Bounds.setText(_translate("MainWindow", "Show inner bounds"))
        self.actionShow_z_Lines.setText(_translate("MainWindow", "Show z-lines"))
        self.actionSave_as.setText(_translate("MainWindow", "Save data..."))
        self.actionHighlight_last_children.setText(_translate("MainWindow", "Highlight last children"))
        self.actionLast_Merge.setText(_translate("MainWindow", "Last Merge"))
        self.actionLast_Children.setText(_translate("MainWindow", "Last Children"))
        self.actionAge.setText(_translate("MainWindow", "Age"))
        self.actionSimilarity.setText(_translate("MainWindow", "Similarity"))
        self.actionSimilar_members_at_point.setText(_translate("MainWindow", "Similar members at point"))
        self.actionMerge_Size.setText(_translate("MainWindow", "Merge Size"))
        self.actionOpen_Preferences.setText(_translate("MainWindow", "Open Preferences..."))
        self.actionLoad_data.setText(_translate("MainWindow", "Load data..."))
        self.actionShow_Timeslices.setText(_translate("MainWindow", "Show time slices"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

